eraware/Eraware.MinimalSkin

- .github/workflows/nodejs.yml
> Setup ci with github actions

- gulpfile.ts
- package.json
- yarn.lock
> Made liveserver url not hardcoded

- gulpfile.ts
- src/containers/default.ascx
> Added containers support

- gulpfile.ts
- package.json
- yarn.lock
> Implemented theme packaging

- .github/workflows/nodejs.yml
- .github/workflows/release-drafter.yml
> Automates release notes drafting

- src/scripts/utilities/utils.ts
> Fixes an issue with class replacement not working

- gulpfile.ts
- src/scripts/main.ts
- src/styles/bootstrap/bootstrap.scss
- theme-settings.ts
Closes #95 
Allows 3 options for bootstrap:
- No bootstrap
- Only grid and responsive utilities
- All of bootstrap
> Allows loading different parts of bootstrap

- .github/workflows/nodejs.yml
> Should fix yarn build

- .github/mergeable.yml
Enforces a PR title, description and milestone for later automating release notes
> Adds mergeable configuration

- theme-settings.ts
Last PR commited the config file change which was unintentional, this reverts it
> Reverts unwanted config change

- .github/workflows/nodejs.yml
Enables CI workflow to be run manually
> Enables CI workflow to be run manually

- package.json
- yarn.lock
As per suggestion at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50428
> Properly bumps types/gulp package

- src/styles/dnn/_dnn.scss
I though I had fixed this but it was fixed wrong. This PR should fix it correctly. Closes Login button text not visible with theme #327
> Fixes the primary action button background

- gulpfile.ts
- src/scripts/menu/menu.ts
- src/styles/skin/_menu.scss
Users can now either hover each menu or click on the chevron in order to expand each menu.
Closes #326
> Implemented mouse support for the menu system

- README.md
- gulpfile.ts
- package.json
- yarn.lock
Migrated to manual versioning for now, need to find a better solution though
> Removed git-tag-version

- .github/mergeable.yml
> testing a pr for pre-release

- build/Build.cs
prevent initial comma in labels list
> prevent initial comma in labels list

- Eraware.MinimalSkin.sln
- package-lock.json
- theme-settings.json
This was sending containers files into the skins folder by mistake
> Fixed an issue with a wrong containers path

- .github/dependabot.yml
Update dependabot.yml to watch for nuget updates
> Update dependabot.yml to watch for nuget updates

- rollup-plugin-browsersync.ts
- rollup.config.dev.ts
Improved typings on rollup plugin browsersync
> Improved typings on rollup plugin browsersync
